// generated by http://json2ts.com/

declare module TidalSearchAPIResponse {

  export interface Artists {
    limit: number;
    offset: number;
    totalNumberOfItems: number;
    items: any[];
  }

  export interface Artist {
    id: number;
    name: string;
    type: string;
    picture?: any;
  }

  export interface Item {
    id: number;
    title: string;
    duration: number;
    streamReady: boolean;
    streamStartDate: Date;
    allowStreaming: boolean;
    premiumStreamingOnly: boolean;
    numberOfTracks: number;
    numberOfVideos: number;
    numberOfVolumes: number;
    releaseDate: string;
    copyright: string;
    type: string;
    version?: any;
    url: string;
    cover: string;
    vibrantColor: string;
    videoCover?: any;
    explicit: boolean;
    upc: string;
    popularity: number;
    audioQuality: string;
    audioModes: string[];
    artists: Artist[];
  }

  export interface Albums {
    limit: number;
    offset: number;
    totalNumberOfItems: number;
    items: Item[];
  }

  export interface Creator {
  }

  export interface PromotedArtist {
    id: number;
    name: string;
    type: string;
    picture: string;
  }

  export interface Item2 {
    uuid: string;
    title: string;
    numberOfTracks: number;
    numberOfVideos: number;
    creator: Creator;
    description: string;
    duration: number;
    lastUpdated: Date;
    created: Date;
    type: string;
    publicPlaylist: boolean;
    url: string;
    image: string;
    popularity: number;
    squareImage: string;
    promotedArtists: PromotedArtist[];
    lastItemAddedAt?: Date;
  }

  export interface Playlists {
    limit: number;
    offset: number;
    totalNumberOfItems: number;
    items: Item2[];
  }

  export interface Artist2 {
    id: number;
    name: string;
    type: string;
    picture: string;
  }

  export interface Album {
    id: number;
    title: string;
    cover: string;
    vibrantColor: string;
    videoCover?: any;
    releaseDate: string;
  }

  export interface Mixes {
    MASTER_TRACK_MIX: string;
    TRACK_MIX: string;
  }

  export interface Item3 {
    id: number;
    title: string;
    duration: number;
    replayGain: number;
    peak: number;
    allowStreaming: boolean;
    streamReady: boolean;
    streamStartDate: Date;
    premiumStreamingOnly: boolean;
    trackNumber: number;
    volumeNumber: number;
    version?: any;
    popularity: number;
    copyright: string;
    url: string;
    isrc: string;
    editable: boolean;
    explicit: boolean;
    audioQuality: string;
    audioModes: string[];
    artists: Artist2[];
    album: Album;
    mixes: Mixes;
  }

  export interface Tracks {
    limit: number;
    offset: number;
    totalNumberOfItems: number;
    items: Item3[];
  }

  export interface Artist3 {
    id: number;
    name: string;
    type: string;
    picture: string;
  }

  export interface Item4 {
    id: number;
    title: string;
    volumeNumber: number;
    trackNumber: number;
    releaseDate: Date;
    imagePath?: any;
    imageId: string;
    vibrantColor: string;
    duration: number;
    quality: string;
    streamReady: boolean;
    streamStartDate: Date;
    allowStreaming: boolean;
    explicit: boolean;
    popularity: number;
    type: string;
    adsUrl?: any;
    adsPrePaywallOnly: boolean;
    artists: Artist3[];
    album?: any;
  }

  export interface Videos {
    limit: number;
    offset: number;
    totalNumberOfItems: number;
    items: Item4[];
  }

  export interface Artist4 {
    id: number;
    name: string;
    type: string;
    picture: string;
  }

  export interface Album2 {
    id: number;
    title: string;
    cover: string;
    vibrantColor: string;
    videoCover?: any;
    releaseDate: string;
  }

  export interface Mixes2 {
    MASTER_TRACK_MIX: string;
    TRACK_MIX: string;
  }

  export interface Creator2 {
  }

  export interface PromotedArtist2 {
    id: number;
    name: string;
    type: string;
    picture: string;
  }

  export interface Value {
    id: number;
    title: string;
    duration: number;
    replayGain: number;
    peak: number;
    allowStreaming: boolean;
    streamReady: boolean;
    streamStartDate: Date;
    premiumStreamingOnly: boolean;
    trackNumber: number;
    volumeNumber: number;
    version?: any;
    popularity: number;
    copyright: string;
    url: string;
    isrc: string;
    editable: boolean;
    explicit: boolean;
    audioQuality: string;
    audioModes: string[];
    artists: Artist4[];
    album: Album2;
    mixes: Mixes2;
    releaseDate: any;
    imagePath?: any;
    imageId: string;
    vibrantColor: string;
    quality: string;
    type: string;
    adsUrl?: any;
    adsPrePaywallOnly?: boolean;
    uuid: string;
    numberOfTracks?: number;
    numberOfVideos?: number;
    creator: Creator2;
    description: string;
    lastUpdated?: Date;
    created?: Date;
    publicPlaylist?: boolean;
    image: string;
    squareImage: string;
    promotedArtists: PromotedArtist2[];
    lastItemAddedAt?: Date;
    numberOfVolumes?: number;
    cover: string;
    videoCover?: any;
    upc: string;
  }

  export interface TopHit {
    value: Value;
    type: string;
  }

  export interface RootObject {
    artists: Artists;
    albums: Albums;
    playlists: Playlists;
    tracks: Tracks;
    videos: Videos;
    genres: any[];
    topHits: TopHit[];
  }
}

